language: go
go:
- 1.12.x
install: make bootstrap
branches:
  only:
  - master
  - "/^v([0-9]+)\\.([0-9]+)\\.([0-9]+)(?:\\-(rc\\.[0-9]+)*)?$/"
env:
  global:
  - MANIFOLD_TEAM=manifold-integration-ci
  # MANIFOLD_API_TOKEN
  - secure: j76bDIOw+vfgABK8NrD4KAwHqZa7LzaI7XMpnTceaxNvTztm9YSc0C2DVUckffgO4kkZ6W12nnmKfIwOL01Zkv7M+dqdnZpEd7lmal6h07rmPORUi1kTQJoaYruHnn+wzI0HvsDmxizKihU3yZ2nRBPyRIJaXX7Fns60TF9QlcWWtofg/ESvhPA4UHt6IRocOU7PikERxUEa25Y8OaXxPR4smmzqibw7quhHbfzs26aHsoDw8qHZzdgSnYY11+9Vy4w4Ieq+DopWJ0Dzq6vDKyd11BWryzBHNpydVF5qfEiWAzWMSGxIZ5u58mTXA2C7okj9H3cIWhqEs/KEqTSFtTlMcdmE9S0CcNGCWNqnWULzV0+JbxQx2H2Gxw/f/fHF1v9+TkOOmUX/t6yzzt4t4RsgK/nQMJqYO2Lzolf1u+qlH1bZ2HUwJxlK9r91lVCEzEJnysZUlbTN20lajFMenXRNVOCpW/bEN/JvOy/8nJdkDHV89gHlxrZ2cRismFX53lKoAQoLJiFD3FSI7MsL2QWyIbXTsnoVo8ap6Y913zDny+x4JmHZCJ/g93FgItoJygHNoCNMmW4fEJP4VFL6SR2OWqooQdICTPU9UqwftwNBW5Hbfo/0fHZLcRVrUM7+nNLWVmDRTYxT8VuRreDUJQc9JCZDc4nXeLnXZwL2nG0=
