apiVersion: v1
kind: Namespace
metadata:
  name: manifold-system

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: credentials-controller
  namespace: manifold-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "manifold-k8s-credentials-controller"
    spec:
      containers:
        - name: credentials-controller
          image: manifoldco/kubernetes-credentials:v0.1.0
          env:
            - name: MANIFOLD_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: manifold-api-secrets
                  key: api_token
            - name: MANIFOLD_TEAM
              valueFrom:
                secretKeyRef:
                  name: manifold-api-secrets
                  key: team
                  optional: true
          resources:
            requests:
              cpu: 100m
              memory: 10Mi
